### ISSUE TITLE
Option to disable link outlines

### ISSUE THREAD

**Issue by ghost** [antonioriva/RegExLink#2]
This is the only open file/URL plugin that just works, after trying more than a couple.
I just have one request, an option to disable link outlines as well. They look good for a couple of links but on a text file with lots of links, it gets noisy. I prefer to use just the gutter marks.

Thanks for the great work.

``` json
{
"regex_link_outlines": false
}
```

EDIT: setting `"style": ""` also disables the gutter marks.

**Comment by mom1** [comment]
Check Pull request

**Comment by ghost** [comment]
@mom1 Thanks. I tried your fork but setting it to false also hides the gutter marks.

**Comment by mom1** [comment]
@megadr01d Check now :relaxed:

**Comment by ghost** [comment]
@mom1 Excellent work, thank you. I added your repo to Package Manager. :+1:
